### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by woolen-sheep** [Warhawk947/DameDaneGenerator#1]
When I ran **python main.py** I got the following errors.
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from firstordermodel.demo import load_checkpoints
  File "E:\Program Files\DameDaneGenerator-master\firstordermodel\demo.py", line 14, in <module>
    from firstordermodel.sync_batchnorm import DataParallelWithCallback
ModuleNotFoundError: No module named 'firstordermodel.sync_batchnorm'

**Comment by woolen-sheep** [comment]
sorry that I didn't find the release.

**Comment by woolen-sheep** [comment]
Well, I have downloaded files in release, but it still throws the error ModuleNotFoundError: No module named 'firstordermodel.sync_batchnorm'.
Maybe you ignored the file when push?

**Comment by navinor** [comment]
hmmm, I'll look into it

**Comment by navinor** [comment]
I fixed it, apparently I didn't upload the sync_batchnorm folder hahaha

redownload the repo, add the tar files, and lmk how it turns out!


thanks, Warhawk947
