### ISSUE TITLE
Is CUDA exclusive or not?

### ISSUE THREAD

**Issue by rk0cc** [Warhawk947/DameDaneGenerator#3]
I'm remember that `first order model` included PyCUDA which make only Nvidia GPU can handle this processes. However, I didn't see hardware requirement on your repository that it still required to run on Nvidia GPU or can be executed on non-Nvidia GPU.

**Comment by navinor** [comment]
oh, sorry haha I forgot to include the gpu requirements
yes, it must be run on a nvidia gpu, sorry about the confusion!

**Comment by navinor** [comment]
I have added a warning saying you need a nvidia gpu. thank you for pointing this out!
